### ISSUE TITLE
LineLogin-ForPHP/src/LineAuthorization.php 問題

### ISSUE THREAD

**Issue by yx1hlqbk** [slps970093/LineLogin-ForPHP#1]
第34行
$url = $host . "?" . http_build_query($parameter) . "&scope=". $scope;
其中得的參數redirect_uri 網址某些字元會被轉換調，導致無法正常到登入介面

redirect_uri 參數為 : http://localhost/test/testfunction

**Comment by slps970093** [comment]
你好 請問你 redirect_uri 是否含有 ?var=val 的字元
目前在 0.5.1 版 已經修正這個問題
